# Generated by Django 4.2.6 on 2023-10-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productID", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "Products",
            },
        ),
    ]
