# Generated by Django 4.2.6 on 2023-10-21 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("searchApp", "0002_products_producttitle_products_seriesid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="productTitle",
        ),
        migrations.RemoveField(
            model_name="products",
            name="seriesID",
        ),
    ]
