# Generated by Django 4.2.6 on 2023-10-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searchApp", "0003_remove_products_producttitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="productTitle",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="seriesID",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
