# Generated by Django 4.2.6 on 2023-10-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searchApp", "0004_products_producttitle_products_seriesid"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="description",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="products",
            name="productImage",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="products",
            name="searchUrl",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="shortDescription",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
