# Generated by Django 4.2.6 on 2023-10-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searchApp", "0005_products_description_products_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="additional1",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="products",
            name="additional2",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="products",
            name="additional3",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="products",
            name="esUrl",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="products",
            name="pniUrl",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="products",
            name="tabData",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
