# Generated by Django 4.2.6 on 2023-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searchApp", "0006_products_additional1_products_additional2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files")),
            ],
        ),
        migrations.AlterField(
            model_name="products",
            name="additional1",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="additional2",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="additional3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="productImage",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="seriesID",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="products",
            name="tabData",
            field=models.TextField(blank=True),
        ),
    ]
