# Generated by Django 4.2.6 on 2023-10-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textId", models.CharField(max_length=50, unique=True)),
                ("categoryTitle", models.CharField(max_length=50, unique=True)),
                ("parrentCategory", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("categoryImage", models.TextField(blank=True)),
                ("breadcrumbTitle", models.CharField(blank=True, max_length=100)),
                ("categoryUrl", models.CharField(blank=True, max_length=100)),
                ("rank", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="Y", max_length=1)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "Category",
            },
        ),
    ]
