"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4f@801od&zqaa6d+wn&c)mthlto4u1e(ze6%5evxqrm-it^2-3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["localhost", "127.0.0.1",'micropumpparts.com','www.micropumpparts.com','*']
ALLOWED_HOSTS = ['*']


CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

CSRF_COOKIE_HTTPONLY = False   # ADMIN LOGIN এর জন্য MUST
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'ckeditor',
    'homeScreen',
    'siteApp',
    'category',
    'searchApp',
    # 'ckeditor',   
    # 'rest_framework',
    # 'api',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware", 
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"
CSRF_COOKIE_SECURE = True
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            'libraries': {
                # Register your custom template tags
                'data_load': 'templatetags.data_load',  # Replace with your module path
            },
        },
        
    },
]

CORS_ALLOWED_ORIGINS = [
    "https://micropumpparts.com",
    "https://www.micropumpparts.com",
    "http://127.0.0.1:56871",
    "http://127.0.0.1:8000",
    "http://192.168.1.7:8000",
    "http://localhost:8000",
    "https://burtprocess.com"
]


CSRF_TRUSTED_ORIGINS = [
    "https://micropumpparts.com",
    "https://www.micropumpparts.com",
    "http://127.0.0.1:56871",
    "http://127.0.0.1:8000",
    "http://192.168.1.7:8000",
    "http://localhost:8000"
]


WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'searchdb_aro',
        'NAME': 'searchdb_sample',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',  # Or the MySQL server hostname
        'PORT': '3306',       # MySQL default port
        'OPTIONS': {
            'sql_mode': 'traditional',
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'searchdb',
#         'USER': 'searchdb',
#         'PASSWORD': 'fAl]9zDJy*H*N5PY',
#         'HOST': '172.17.0.1',  # Or the MySQL server hostname
#         'PORT': '53306',       # MySQL default port
#         'OPTIONS': {
#             'sql_mode': 'traditional',
#         }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# MEDIA_URL = '/media/'
# MEDIA_ROOT = [os.path.join(BASE_DIR, 'media')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

 

CKEDITOR_UPLOAD_PATH = "uploads/"
LOGOUT_REDIRECT_URL = 'logged-out'
# CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'Custom',  # You can customize the toolbar
#         'height': 300,
#         # Other CKEditor configurations...
#     },
# }
